name: 'deployNugetPackages'

on:
  push:
    branches:
    - main
    - 'release/**'
  pull_request:
   branches:
    - main
    - 'release/**'

  workflow_dispatch:

env:
  VERSION_SUFFIX: ${{ github.ref_name }}
  HEADREF: ${{ github.head_ref }}
  PACKOUTDIR: ${{ github.workspace }}\packoutput
                    
jobs:
  deploy:
    name: 'Deploy packages'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
     - name: 'echo VERSION_SUFFIX'
       shell: bash
       run: echo ${{ env.VERSION_SUFFIX }}

     - name: 'echo HEADREF '
       shell: bash
       run: echo ${{ env.HEADREF }}

     - name: 'echo github.ref_name'
       if: ${{ github.ref_name }} == 'mainX'
       shell: bash
       run: echo ${{ github.ref_name }}

     - name: 'Set VERSION_SUFFIX: dev'
       if: ${{ github.ref_name }} == 'main'
       shell: bash
       run: echo "VERSION_SUFFIX=dev" >> $GITHUB_ENV

     - name: 'Set VERSION_SUFFIX: string.Empty'
       if: ${{ startsWith(github.ref_name, 'release/') }}
       shell: bash
       run: echo "VERSION_SUFFIX=" >> $GITHUB_ENV

     - name: 'Set VERSION_SUFFIX: alpha'
       if: ${{ startsWith(github.ref_name, 'release/alpha') }}
       shell: bash
       run: echo "VERSION_SUFFIX=alpha" >> $GITHUB_ENV

     - name: 'Set VERSION_SUFFIX: beta'
       if: ${{ startsWith(github.ref_name, 'release/beta') }}
       shell: bash
       run:  echo "VERSION_SUFFIX=beta" >> $GITHUB_ENV

     - name: 'Checkout'
       uses: actions/checkout@v4
     
     - name: 'Install dotnet'
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: '8.0.x'

     - name: 'Add GitHub to Nuget source'
       uses: 'Andre-Loetzsch/actions/addGitHubToNugetSource@v1'
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Build and test Oleander.AssemblyVersioning.sln'
       uses: Andre-Loetzsch/actions/buildAndTestSolution@v1
       with:
         solution: '${{ github.workspace }}\Oleander.Assembly.Versioning.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         packoutdir: ${{ env.PACKOUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'delete Oleander.Assembly.Versioning.Tool-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Assembly.Versioning.Tool'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"

     - name: 'delete Oleander.Assembly.Versioning.BuildTask-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Assembly.Versioning.BuildTask'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"


     - name: 'delete Oleander.Assembly.Versioning-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Assembly.Versioning'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"


     - name: 'delete Oleander.Assembly.Comparator-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Assembly.Comparator'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"


     - name: 'delete Oleander.Assembly.Comparers-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Assembly.Comparers'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"

     - name: 'push nuget packages'
       if: matrix.os == 'windows-latest' && github.event_name != 'pull_request'
       uses: Andre-Loetzsch/actions/pushNugetPackages@v1
       with:
         outdir: ${{ env.PACKOUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'push nuget packages to nuget gallery'
       if: matrix.os == 'windows-latest' && github.event_name == 'pull_request' && env.VERSION_SUFFIX == 'devX'
       uses: Andre-Loetzsch/actions/pushNugetPackagesToNugetOrg@v1
       with:
         packagedir: ${{ env.PACKOUTDIR }}
         nuget_apikey: ${{ secrets.NUGETORG_ACCESS_TOKEN }}
